# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageRGB.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageRGB(object):
    def setupUi(self, ImageRGB):
        ImageRGB.setObjectName("ImageRGB")
        ImageRGB.resize(590, 375)
        ImageRGB.setMinimumSize(QtCore.QSize(590, 375))
        ImageRGB.setMaximumSize(QtCore.QSize(590, 375))
        ImageRGB.setSizeIncrement(QtCore.QSize(0, 0))
        ImageRGB.setBaseSize(QtCore.QSize(590, 375))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        ImageRGB.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImageRGB)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(ImageRGB)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.OpenImageBtn = QtWidgets.QPushButton(self.frame)
        self.OpenImageBtn.setBaseSize(QtCore.QSize(0, 19))
        self.OpenImageBtn.setObjectName("OpenImageBtn")
        self.horizontalLayout.addWidget(self.OpenImageBtn)
        self.verticalLayout.addWidget(self.frame)
        self.line = QtWidgets.QFrame(ImageRGB)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.tabWidget = QtWidgets.QTabWidget(ImageRGB)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.PreImage = QtWidgets.QWidget()
        self.PreImage.setObjectName("PreImage")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.PreImage)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.PreImage)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.PreView = QtWidgets.QLabel(self.groupBox)
        self.PreView.setText("")
        self.PreView.setObjectName("PreView")
        self.horizontalLayout_5.addWidget(self.PreView)
        self.horizontalLayout_3.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.PreImage)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.PreImage)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.PreImage)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.horizontalSlider = QtWidgets.QSlider(self.PreImage)
        self.horizontalSlider.setEnabled(False)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_2.addWidget(self.horizontalSlider)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.GetPixelsBtn = QtWidgets.QPushButton(self.PreImage)
        self.GetPixelsBtn.setObjectName("GetPixelsBtn")
        self.horizontalLayout_4.addWidget(self.GetPixelsBtn)
        self.PixelsToUiStrBtn = QtWidgets.QPushButton(self.PreImage)
        self.PixelsToUiStrBtn.setObjectName("PixelsToUiStrBtn")
        self.horizontalLayout_4.addWidget(self.PixelsToUiStrBtn)
        self.horizontalLayout_4.setStretch(0, 9)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_3.setStretch(0, 6)
        self.horizontalLayout_3.setStretch(2, 2)
        self.tabWidget.addTab(self.PreImage, "")
        self.RGBtoHEX = QtWidgets.QWidget()
        self.RGBtoHEX.setEnabled(False)
        self.RGBtoHEX.setObjectName("RGBtoHEX")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.RGBtoHEX)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.RGBtoHEX)
        self.textBrowser.setReadOnly(False)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_2.addWidget(self.textBrowser)
        self.tabWidget.addTab(self.RGBtoHEX, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 10)

        self.retranslateUi(ImageRGB)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ImageRGB)

    def retranslateUi(self, ImageRGB):
        _translate = QtCore.QCoreApplication.translate
        ImageRGB.setWindowTitle(_translate("ImageRGB", "图片像素提取"))
        self.OpenImageBtn.setText(_translate("ImageRGB", "打开图片"))
        self.groupBox.setTitle(_translate("ImageRGB", "预览"))
        self.radioButton_3.setText(_translate("ImageRGB", "100*100像素"))
        self.radioButton_2.setText(_translate("ImageRGB", "50*50像素"))
        self.radioButton.setText(_translate("ImageRGB", "原尺寸缩放"))
        self.GetPixelsBtn.setText(_translate("ImageRGB", "像素提取"))
        self.PixelsToUiStrBtn.setText(_translate("ImageRGB", "像素提取转UI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PreImage), _translate("ImageRGB", "像素提取"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RGBtoHEX), _translate("ImageRGB", "像素文本"))


