# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageRGB.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageRGB(object):
    def setupUi(self, ImageRGB):
        ImageRGB.setObjectName("ImageRGB")
        ImageRGB.resize(590, 375)
        ImageRGB.setMinimumSize(QtCore.QSize(590, 375))
        ImageRGB.setMaximumSize(QtCore.QSize(590, 375))
        ImageRGB.setSizeIncrement(QtCore.QSize(0, 0))
        ImageRGB.setBaseSize(QtCore.QSize(590, 375))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        ImageRGB.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImageRGB)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(ImageRGB)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.OpenImageBtn = QtWidgets.QPushButton(self.frame)
        self.OpenImageBtn.setBaseSize(QtCore.QSize(0, 19))
        self.OpenImageBtn.setObjectName("OpenImageBtn")
        self.horizontalLayout.addWidget(self.OpenImageBtn)
        self.verticalLayout.addWidget(self.frame)
        self.line = QtWidgets.QFrame(ImageRGB)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.tabWidget = QtWidgets.QTabWidget(ImageRGB)
        self.tabWidget.setObjectName("tabWidget")
        self.PreImage = QtWidgets.QWidget()
        self.PreImage.setObjectName("PreImage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.PreImage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_1 = QtWidgets.QRadioButton(self.PreImage)
        self.radioButton_1.setEnabled(False)
        self.radioButton_1.setObjectName("radioButton_1")
        self.horizontalLayout_3.addWidget(self.radioButton_1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.PreImage)
        self.radioButton_2.setEnabled(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_3.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.PreImage)
        self.radioButton.setEnabled(False)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.GetRGBBtn = QtWidgets.QPushButton(self.PreImage)
        self.GetRGBBtn.setEnabled(False)
        self.GetRGBBtn.setBaseSize(QtCore.QSize(0, 18))
        self.GetRGBBtn.setCheckable(False)
        self.GetRGBBtn.setAutoDefault(False)
        self.GetRGBBtn.setObjectName("GetRGBBtn")
        self.horizontalLayout_3.addWidget(self.GetRGBBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.frame_3 = QtWidgets.QFrame(self.PreImage)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.orgin = QtWidgets.QLabel(self.groupBox)
        self.orgin.setMinimumSize(QtCore.QSize(165, 165))
        self.orgin.setMaximumSize(QtCore.QSize(165, 165))
        self.orgin.setBaseSize(QtCore.QSize(165, 165))
        self.orgin.setText("")
        self.orgin.setObjectName("orgin")
        self.horizontalLayout_5.addWidget(self.orgin)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.thumb_100 = QtWidgets.QLabel(self.groupBox_2)
        self.thumb_100.setMinimumSize(QtCore.QSize(165, 165))
        self.thumb_100.setMaximumSize(QtCore.QSize(165, 165))
        self.thumb_100.setBaseSize(QtCore.QSize(165, 165))
        self.thumb_100.setText("")
        self.thumb_100.setObjectName("thumb_100")
        self.horizontalLayout_6.addWidget(self.thumb_100)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.thumb_50 = QtWidgets.QLabel(self.groupBox_3)
        self.thumb_50.setMinimumSize(QtCore.QSize(165, 165))
        self.thumb_50.setMaximumSize(QtCore.QSize(165, 165))
        self.thumb_50.setBaseSize(QtCore.QSize(165, 165))
        self.thumb_50.setText("")
        self.thumb_50.setObjectName("thumb_50")
        self.horizontalLayout_7.addWidget(self.thumb_50)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_2.setStretch(1, 1)
        self.tabWidget.addTab(self.PreImage, "")
        self.RGBtoHEX = QtWidgets.QWidget()
        self.RGBtoHEX.setObjectName("RGBtoHEX")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.RGBtoHEX)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.RGBtoHEX)
        self.textBrowser.setReadOnly(False)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_2.addWidget(self.textBrowser)
        self.tabWidget.addTab(self.RGBtoHEX, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 9)

        self.retranslateUi(ImageRGB)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ImageRGB)

    def retranslateUi(self, ImageRGB):
        _translate = QtCore.QCoreApplication.translate
        ImageRGB.setWindowTitle(_translate("ImageRGB", "图片像素提取"))
        self.OpenImageBtn.setText(_translate("ImageRGB", "打开图片"))
        self.radioButton_1.setText(_translate("ImageRGB", "100*100像素"))
        self.radioButton_2.setText(_translate("ImageRGB", "50*50像素"))
        self.radioButton.setText(_translate("ImageRGB", "原尺寸像素"))
        self.GetRGBBtn.setText(_translate("ImageRGB", "开始提取像素"))
        self.groupBox.setTitle(_translate("ImageRGB", "原图预览"))
        self.groupBox_2.setTitle(_translate("ImageRGB", "100*100"))
        self.groupBox_3.setTitle(_translate("ImageRGB", "50*50"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PreImage), _translate("ImageRGB", "像素提取"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RGBtoHEX), _translate("ImageRGB", "像素文本"))


