# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 640)
        MainWindow.setMinimumSize(QtCore.QSize(480, 640))
        MainWindow.setMaximumSize(QtCore.QSize(480, 640))
        MainWindow.setSizeIncrement(QtCore.QSize(480, 640))
        MainWindow.setBaseSize(QtCore.QSize(480, 640))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PathTxt = QtWidgets.QTextEdit(self.groupBox)
        self.PathTxt.setMinimumSize(QtCore.QSize(0, 30))
        self.PathTxt.setBaseSize(QtCore.QSize(0, 30))
        self.PathTxt.setReadOnly(True)
        self.PathTxt.setObjectName("PathTxt")
        self.horizontalLayout_2.addWidget(self.PathTxt)
        self.horizontalLayout.addWidget(self.groupBox)
        self.OpenDirBtn = QtWidgets.QPushButton(self.frame)
        self.OpenDirBtn.setEnabled(False)
        self.OpenDirBtn.setObjectName("OpenDirBtn")
        self.horizontalLayout.addWidget(self.OpenDirBtn)
        self.horizontalLayout.setStretch(0, 9)
        self.verticalLayout_2.addWidget(self.frame)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.YCPTAB = QtWidgets.QTabWidget(self.centralwidget)
        self.YCPTAB.setObjectName("YCPTAB")
        self.YCPGAME = QtWidgets.QWidget()
        self.YCPGAME.setObjectName("YCPGAME")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.YCPGAME)
        self.verticalLayout.setObjectName("verticalLayout")
        self.YCPGAMETREE = QtWidgets.QTreeView(self.YCPGAME)
        self.YCPGAMETREE.setObjectName("YCPGAMETREE")
        self.verticalLayout.addWidget(self.YCPGAMETREE)
        self.YCPTAB.addTab(self.YCPGAME, "")
        self.YCPCOMP = QtWidgets.QWidget()
        self.YCPCOMP.setObjectName("YCPCOMP")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.YCPCOMP)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.YCPCOMPTREE = QtWidgets.QTreeView(self.YCPCOMP)
        self.YCPCOMPTREE.setObjectName("YCPCOMPTREE")
        self.verticalLayout_3.addWidget(self.YCPCOMPTREE)
        self.YCPTAB.addTab(self.YCPCOMP, "")
        self.YLANDFILE = QtWidgets.QWidget()
        self.YLANDFILE.setObjectName("YLANDFILE")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.YLANDFILE)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.YLANDFILETREE = QtWidgets.QTreeView(self.YLANDFILE)
        self.YLANDFILETREE.setObjectName("YLANDFILETREE")
        self.horizontalLayout_3.addWidget(self.YLANDFILETREE)
        self.YCPTAB.addTab(self.YLANDFILE, "")
        self.verticalLayout_2.addWidget(self.YCPTAB)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(2, 12)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 18))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionRGB = QtWidgets.QAction(MainWindow)
        self.actionRGB.setObjectName("actionRGB")
        self.Login = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.Login.setFont(font)
        self.Login.setObjectName("Login")
        self.RGB = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.RGB.setFont(font)
        self.RGB.setObjectName("RGB")
        self.menu.addAction(self.Login)
        self.menu.addAction(self.RGB)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.YCPTAB.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "艾兰岛盒子"))
        self.groupBox.setTitle(_translate("MainWindow", "YCP游戏目录地址"))
        self.OpenDirBtn.setText(_translate("MainWindow", "打开目录"))
        self.YCPTAB.setTabText(self.YCPTAB.indexOf(self.YCPGAME), _translate("MainWindow", "YCP游戏"))
        self.YCPTAB.setTabText(self.YCPTAB.indexOf(self.YCPCOMP), _translate("MainWindow", "YCP组件"))
        self.YCPTAB.setTabText(self.YCPTAB.indexOf(self.YLANDFILE), _translate("MainWindow", "YLAND文件"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.action.setText(_translate("MainWindow", "denglu "))
        self.actionRGB.setText(_translate("MainWindow", "RGB"))
        self.Login.setText(_translate("MainWindow", "登录QQ"))
        self.RGB.setText(_translate("MainWindow", "提取图像像素"))


